#! /bin/bash
python pp_consumer.py \
    --output_dir "result" \
    --logging_dir "./logger" \
    --pretrained_model "Qwen-Image-Edit-2509" \
    --rank 64 \
    --adam_beta1 0.9 \
    --adam_beta2 0.999 \
    --adam_weight_decay 0.01 \
    --adam_epsilon 1e-8 \
    --epochs 1000 \
    --train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --max_train_steps 5000 \
    --lr_warmup_steps 300 \
    --lr_scheduler constant_with_warmup \
    --learning_rate 3e-4 \
    --num_workers 4 \
    --max_grad_norm 1.0 \
    --checkpointing_steps 200 \
    --txt_cache_dir "cache/text_embs/" \
    --img_cache_dir "cache/img_embs/" \
    --control_img_cache_dir "img_embs_control/"